package com.algorithms.aspects;

import org.aspectj.lang.annotation.Aspect;
import org.aspectj.lang.annotation.Before;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

@Aspect
@Component
public class StartSortAspect {

    private static final Logger log = LoggerFactory.getLogger(StartSortAspect.class);

    @Before(
            "execution(void sort())"
    )
    public void printOnStartUp() {
        log.info("Generated by aspect");
    }
}
